language: node_js
node_js:
- "node"
addons:
  sonarcloud:
    organization: "$SONAR_ORGANIZATION"
    token:
      secure: "$SONAR_TOKEN"
install:
- npm install
script:
- npm run test
- npm run test:e2e
- sonar-scanner
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  on:
    tags: true
    repo: MatheusRBarbosa/stopots
    branches:    
      only:      
        - master
  app:
    develop: api-stopots